"use strict"


rpg.lists = {
  stones:["alabaster", "soapstone", "chlorite", "wonderstone", "limestone", "onyx", "obsidian", "marble", "moonstone", "coral", "amber"],
  metals:[
    "mithril",
    "high gold",
    "royal gold",
    "gold",
    "crown gold",
    "green gold",
    "rose gold",
    "electrum",
    "white gold",
    "adamantine",
    "high silver",
    "silver",
    "high steel",
    "steel",
    "meteorite iron",
    "bronze",
    "blood alloy",
    "brass",
    "white copper",
    "copper",
    "cast iron",
    "wrought iron",
    "iron",
    "pewter",
    "lead",
    "tin",
  ],
  gems:["ruby", "sapphire", "crystal", "amethyst", "emerald", "diamond", "opal", "moonstone", "chrysoberyl", "garnet", "jade", "onyx", "sunstone", "topaz", "tourmaline", "turquoise"],
  colours:["red", "blue", "green", "yellow", "purple", "pink", "orange", "brown", "black", "white", "gray", "gold", "silver", "navy blue", "sky blue", "lime green", "teal", "indigo", "magenta", "violet", "khaki", "salmon", "crimson", "lavender", "plum", "olive", "cyan", "maroon", "beige"],
  icons:[
    "a panda",
    "a tiger",
    "a dolphin",
    "a T. rex",
    "a chameleon",
    "a fat cat",
    "a lobster",
    "a snake",
    "a red demon with horns",
    "a zombie",
    "a sunflower",
    "a stylised tree",
    "an oak tree",
    "a large banana",
    "a turnip with a face",
    "a skull",
    "a heart with a dagger in it",
    "a screaming face",
    "a lightning strike",
    "a solar eclipse",
    "an erupting volcano",
    "a pot of ink with a quill in it",
    "artful blobs of colour",
    "a lightning strike",
  ],
}