"use strict"
walkthroughs.b = [




    // You can try heading north or south, but will not get anywhere. You can try looking in windows, knocking o the door. What you need to do is get the letter, and then you can head east.
    "get letter",
    "east",
    "east",
    // Inside house, the can wonder most of it from the start, but you cannot get out. Or get back to this room. You might want to check out the paintings while you are here, before heading north, where you can find a key.
    "north",
    "x clock",
    "x key",
    "get key",
    // Go to the solar and grab the chamber pot, then go down to the lab
    "west",
    "south",
    "get pot",
    // Now smash a window. In fact, you can smash a window in many rooms, so take your pick. Grab a shard of the broken glass.
    "smash window",
    "get shard",
    // Head into the drawing room. There are two ways in, you can also go south, and then east from there. Whichever you go in first will be the "small" way - you will be tiny, the room will be huge. When you go in other way, you will be normal size. This allows up to change the size of objects! Take a look around.
    "north",
    "east",
    "south",
    "east",
    "northeast",
    "x cab",
    "x cracks",
    // So there is a hole behind the cabinet, but it is way too big to move...
    "southwest",
    "west",
    "south",
    // Now when we go into the drawing room it will be normal sized, and we can move the cabinet. And if we drop the key, we can make it bigger.
    "east",
    "x cab",
    "shift cab",
    "drop key",
    // With the cabinet shifted, you can go into the drawing room when you are tiny. The key is now big - take it
    "west",
    "north",
    "east",
    "get key",
    // Now we can go in the hole in the wall and get the boots
    "northeast",
    "x cab",
    "x cracks",
    "north",
    "get boots",
    "south",
    "southwest",
    // The boots have a hole in them, and we need to get them fixed. Before we do that, we need to make them small. Drop the boots here, and pick them up when you are big and the boots will be smaller
    "drop boots",
    "west",
    "south",
    "east",
    "get boots",
    // We will come back to the boots later. For now, head to the theatre
    "west",
    "west",
    "sw",
    "x man",
    // This guy is clockwork, but we have a key and can wind him up
    "put key in man",
    "wind up man",
    "talk to man",
    // So we need to solve the guy's riddle... Or rather Mandy does. If only she had a copy of Hamlet. She does have a book, and it changes, depending on where she is. She needs to go to the castle-like section, and look at it there
    "ne",
    "east",
    "south",
    "east",
    "east",
    "east",
    "x hamlet",
    // Great! Now back to the clockwork thespian
    "west",
    "west",
    "west",
    "north",
    "west",
    "nw",
    "talk to man",
    // Hmm, some of his text is in green. Is that a clue?
    // Anyway, head to the chess board, and turn the knight
    "ne",
    "east",
    "north",
    "turn knight",
    // Mandy is outside! But not home. Still, she can go south and get sand, and then southwest to get an oar.
    "south",
    "fill pot",
    "south",
    "x pot",
    "sw",
    "x boat",
    "x oar",
    "get oar",
    // Head back to the dead horse, and use the oar to turn it
    "ne",
    "north",
    "turn horse",
    // Now we can fix theboots, take them to the nursery.
    "north",
    "west",
    "north",
	  // There is a guy in the dolls house who can help. Open the dolls house to find him. Note, however, that there is a balloon here that will cause time to loop back it it touches the floor. Make sure you knock it every few rounds.
    "open dolls",
    "talk to man",
    "ask man about boots",
    "get balloon",
    "give boots to man",
    "wait",
    "wait",
    "get balloon",
    "wait",
    "get boots",
    // Great, the boots are fixed - we will use them later. Go down to the lab
    "south",
    "down",
    "down",
    // Kind of like Frankinstein's monster... We need to animate it, and that takes lightning. Grab the wire and head up to the observatory - the other end is already attached to the device.
    "get wire",
    "up",
    "up",   
    "up",
    // We need to get on the roof of the great hall, which is to the west, by climbing the telescope, but you need to set the telescope up just right.
    "x controls",
    "x telescope",
    // You will need to pull the lever to open the ceiling, turn the right wheel to the left twice to lower the telescope, then turn the left whhel to the left three times to point the telescope west.
    "pull lever",
    "turn right left",
    "turn right left",
    "turn left left",
    "turn left left",
    "turn left left",
    "x telescope",
    // Now we can climb up, and head west, onto the roof, where we can tie the wire to the weather vane
    "climb",
    "west",
    "west",
    "tie wire to vane",
    // Now head back before you get struck by lightning! Go back down to the lab, and look at the coprse
    "east",
    "east",
    "down",
    "down",
    "down",
    "down",
    "Look at animated corpse",
    // He will not do anything until the boots are sorted. We already got them repaired, but they are too small, and have something in them too.
    "up",
    "up",
    "east",
    "south",
    "south",
    "east",
    // To get the thing out of the boots we need to make them really big...
    "drop boots",
    "west",
    "north",
    "east",
    "get boots",
    "west",
    "south",
    "east",
    "x boots",
    "drop boots",
    "west",
    "north",
    "east",
    // Now go inside boots, and get the piece of card
    "in",
    "get card",
    "x card",
    "read card",
    "l",
    "out",
    // Now we want both card and the boots to be smaller...
    "drop card",
    "west",
    "south",
    "east",
    "take boots",
    "take paper",
    // Now heads back to Patch
    "west",
    "south",
    "east",
    "east",
    "east",
    "down",
    "down",
    "give boots to patch",
    // Patch will now be happy to follow you! This is good because he will catch any tamarind pods that fall his way - and stop any silvery people from stealing them! Lead him to the tamrind tree, tell him to wait, then go to the balcony above and shake tree.
    "p,follow",
    "up",
    "west",
    "patch,wait",
    "east",
    "up",
    "west",
    "shake tree",
    // Now go down and get the pod from Patch, and use the glass shard to get the seeds
    "east",
    "down",
    "west",
    "patch,give me pod",
    "open pod",
    "west",
    // We need to plant a seed in the bare earth, then turn the hourglass, let the plant grow, and climb the tree to get up to the lift above Mandy
    "plant 1 seeds in ground",
    "turn ho",
    "wait",
    "wait",
    "climb tree",
    // So that failed... We need to increase the growing time. Do that by enlarging the hourglass and also by putting in more sand, which fortunately we already have. We need to enlasrge both twice.
    "get ho",
    "west",
    "west",
    "west",
    "south",
    "south",
    "east",
    "drop pot",
    "drop h",
    "west",
    "north",
    "east",
    "get all",
    "west",
    "south",
    "east",
    "drop pot",
    "west",
    "north",
    "east",
    "get po",
    "drop ho",
    // You will not be able to pour the sand in directly. You could make the hourglass bigger, then pour in the sand, then make it not so big, but a better way is to make the piece of paper ito a funnel.
    "make funnel",
    "put funnel in ho",
    "pour sand into ho",
    "get ho",
    // We should be good to go
    "west",
    "north",
    "east",
    "east",
    "east",
    "put ho on ped",
    "plant 1 seed",
    "turn ho",
    "wait",
    "wait",
    "wait",
    "wait",
    "wait",
    "wait",
    "wait",
    "wait",
    "wait",
    "wait",
    "wait",
    "wait",
    // We have a tree! But we still need help as there are no branches at the bottom. You could climb over from the catwalk, but we will use Patch. Once up the tree, go southeast to get to the lift, then go out of the lift.
    "east",
    "patch,follow",
    "west",
    "patch,hug tree",
    "up",
    "southwest",
    "out",
    // At last we have found Melewiez and you can give him the letter! You might want to ask him about other things
    "get letter from bag",
    "give letter to mal",
    "ask mal about a way out",
    // More green writing! Another clue?
    // Head north to talk to the house. You can ask the house about various things, but it is not very helpful. What you do need to do is answer the riddle. All the green writing was song titles, which, tiogether with her bag, means the answer must be "one direction".
    "north",
    "ask mal about riddle",
    "say one",
    // The house is back to normal, and everything is fine. Head west to end the game.
    "west",




]